name: flutter_windows_angle_opengl_es
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterWindowsAngleOpenglEsPluginCApi
